application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      milo-fg:
        license: Apache-2.0
        inputs:
          fgSite: $FG_SITE
          fgClientId: $FG_CLIENT_ID
          fgAuthority: $FG_AUTHORITY
        actions:
          copy:
            function: actions/copy/copy.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
          copy-worker:
            function: actions/copy/worker.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
          promote:
            function: actions/promote/promote.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
          promote-worker:
            function: actions/promote/worker.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
          status:
            function: actions/status/status.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
